apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  description: ${{values.description}}
  annotations:
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - javascript
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner}}
  system: demo-system
  providesApis:
    - ${{values.component_id}}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id}}-api
  description: API for ${{values.component_id}}
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner}}
  definition: |
    openapi: 3.0.0
    info:
      title: ${{values.component_id}} API
      version: 1.0.0
    paths:
      /health:
        get:
          summary: Health check
          responses:
            '200':
              description: Service is healthy
